### ISSUE TITLE
Can you please expand the README.md?

### ISSUE THREAD

**Issue by cowchimp** [resin-io-playground/node-red-contrib-resinio#1]
Hi.

As a fan of both resin.io and node-red I'm interested in this project but the README.md doesn't really explain what can be done with it.
A short explanation for each of the nodes it exposes will go a long way.

Thanks!

**Comment by curcuz** [comment]
hey @cowchimp this projects is under heavy development atm (as you can see from the commits history) - I will totally add proper documentation for this in the upcoming days, will ping you here as soon as done

**Comment by curcuz** [comment]
@cowchimp added proper documentation to the README ;)

**Comment by cowchimp** [comment]
Thank you! It's much clearer now (and I'm already thinking of how I'm going to combine resin and node-red...)

**Comment by curcuz** [comment]
great! let us know how it goes on the [forum](https://forums.resin.io/) or  on [gitter](https://gitter.im/resin-io/chat) ! :sunglasses:
